// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBii5vo5IDn7qFf0gGs7qX2zuHzZdGBZM',
    appId: '1:522148405522:android:19f0e9c23173d60d2053cb',
    messagingSenderId: '522148405522',
    projectId: 'hydrogrow-52aca',
    databaseURL: 'https://hydrogrow-52aca-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hydrogrow-52aca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-efFRPNV95Ydc5vieFZbfoh5Jtrgq5qk',
    appId: '1:522148405522:ios:2fcaeb0dee7f37962053cb',
    messagingSenderId: '522148405522',
    projectId: 'hydrogrow-52aca',
    databaseURL: 'https://hydrogrow-52aca-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hydrogrow-52aca.firebasestorage.app',
    iosBundleId: 'dev.hydroapp.hydroGrow',
  );
}
